// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128182710_AuditMigrations")]
    partial class AuditMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Apprentice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprenticeAchievement")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeClassification")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeConfirmation")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeEthnicity")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeGender")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeNonCompletionReason")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeProgram")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeProgression")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeshipDelivery")
                        .HasColumnType("text");

                    b.Property<string>("CertificatesReceived")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Directorate")
                        .HasColumnType("text");

                    b.Property<string>("DoeReference")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndPointAssessor")
                        .HasColumnType("text");

                    b.Property<bool>("IsCareLeaver")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("ManagerTitle")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PauseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Post")
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAgreedApprenticeshipPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("TrainingCourse")
                        .HasColumnType("text");

                    b.Property<string>("TrainingProvider")
                        .HasColumnType("text");

                    b.Property<decimal?>("UKPRN")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ULN")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("WithdrawalDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ULN")
                        .IsUnique();

                    b.ToTable("Apprentices");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTypeTargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityName");

                    b.HasIndex("EventType");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprenticeName")
                        .HasColumnType("text");

                    b.Property<string>("ApprenticeshipTrainingCourse")
                        .HasColumnType("text");

                    b.Property<int?>("CourseLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EnglishPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GovernmentContribution")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LevyDeclared")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidFromLevy")
                        .HasColumnType("numeric");

                    b.Property<string>("PayeScheme")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PayrollMonth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TenPercentageTopUp")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("TrainingProvider")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ULN")
                        .HasColumnType("numeric");

                    b.Property<decimal>("YourContribution")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
